name: Seattle Wedding DJ
favicon: null
layout_spectrum: 0.36088
typography_spectrum: 0.4291
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#6b85fe'
    - '#2f2f2f'
    - '#cecece'
  brandStrength: 0.019195398781448603
  lightness: 0.53121780580841
  saturation: 0.6875
  rhythmicContrast: 0.42293103504925966
purpose: []
